### ISSUE TITLE
Does not work with npm3 new Flatness

### ISSUE THREAD

**Issue by vanthome** [reworkcss/rework-npm#21]
For our [VCL](https://github.com/vcl/doc), we have an [Icon Module](https://github.com/vcl/icon) which is using a [Font Awesome integration module](https://github.com/vcl/font-awesome) to shim the `style` property. The font awesome module works but the Icon module doesn't as it expects the font awesome module's style here `icon/node_modules/vcl-font-awesome/node_modules/font-awesome/css/font-awesome.css` but it is here `icon/node_modules/font-awesome/css/font-awesome.css`. This means the module does not consider the flatness introduces with NPM 3.

@fiws FYI.

**Comment by conradz** [comment]
The problem is [this line](https://github.com/vcl/font-awesome/blob/master/index.styl#L1). It should read `@import "font-awesome/css/font-awesome.css";`. Since it is using the relative require using the `./`, it will not look in the `node_modules` folder of parent directories, which will cause this problem.

**Comment by fiws** [comment]
Edit: @conradz was faster ;)

I just tested this. And this probably is not an issue of rework-npm. 
rework-npm uses resolve which reports :

```
Error: Cannot find module './node_modules/font-awesome/css/font-awesome.css' from '/home/fiws/vcl-button/node_modules/vcl-font-awesome'
```

the first path is **not** the resolved one. 
So this resolves to `/home/fiws/vcl-button/node_modules/vcl-font-awesome/node_modules/font-awesome/css/font-awesome.css` which does not exist, when installing with npm@3.

The problem is that we used an [relative path](https://github.com/vcl/font-awesome/blob/98fbe65844aae00d20975a78f65e2877aaba58c7/index.styl#L1) in our vcl-font-awesome module.

@vanthome if your error does not look like this, then you might still had `node_modules` installed before testing npm@3 or my setup is different.

**Comment by vanthome** [comment]
@fiws I have the same error and of course installed again with npm3.

**Comment by vanthome** [comment]
@conradz ok, please close for now, as your hint seems to work.
